# `📅DAY_05` _기초 AI Programming

### 피봇 테이블

- 원래 복잡한 표 데이터를 쉽게 정리하고 요약해서 볼 수 있도록 도와주는 기능

#### 피봇 테이블 만드는 법
```python
# 피봇 테이블을 만드는 형식 (기본)
데이터프레임.pivot_table(index='행이 될 열 이름', values='계산할 열 이름', aggfunc='계산방법')
```

- **index**(인덱스): **어떤 기준**으로 데이터를 볼 지 정하는 곳
- **values**(밸류): 어떤 **숫자 데이터를 계산**할 지 정함.
- **aggfunc**(계산방법): 데이터 값을 어떻게 요약할 지 정하는 부분

In [1]:
# 예제

import pandas as pd

data = {
    '손님': ['철수', '영희', '민수', '철수', '영희', '민수'],
    '메뉴': ['피자', '피자', '피자', '햄버거', '햄버거', '햄버거'],
    '개수': [2, 1, 3, 2, 2, 1]
}

df = pd.DataFrame(data)
print(df)
print()


# 메뉴별로 총 개수 계산하기

# 메뉴별로 판매된 개수를 합산해서 새로운 표로 만들기
pivot_menu = df.pivot_table(
    index='메뉴',
    values='개수',
    aggfunc='sum'
)

print(pivot_menu)
print()


# 손님별로 총 주문 수량 계산하기

# 손님별 총 주문한 개수 합산
pivot_customer = df.pivot_table(
    index='손님',
    values='개수',
    aggfunc='sum'
)

print(pivot_customer)
print()


# 메뉴별로 평균 계산하기

# 메뉴가 주문될 때마다 평균적으로 몇 개씩 주문하는지 피봇 테이블 만들기
pivot_mean = df.pivot_table(
    index='메뉴',
    values='개수',
    aggfunc='mean'
)

print(pivot_mean)

   손님   메뉴  개수
0  철수   피자   2
1  영희   피자   1
2  민수   피자   3
3  철수  햄버거   2
4  영희  햄버거   2
5  민수  햄버거   1

     개수
메뉴
피자    6
햄버거   5

    개수
손님
민수   4
영희   3
철수   4

           개수
메뉴
피자   2.000000
햄버거  1.666667

### 크로스탭(crosstab)

- 두 가지 항목 사이의 관계를 쉽게 정리해서 보여주는 표를 만드는 기능

#### crosstab 형식

```python
pd.crosstab(표의 행으로 나올 항목, 표의 열로 나올 항목)
```
- 첫 번째 항목: 표의 가로줄(행)에 나올 항목
- 두 번째 항목: 표의 세로줄(열)에 나올 항목

In [2]:
# 예제

import pandas as pd

data = {
    '성별': ['남자', '여자', '남자', '여자', '남자', '여자', '남자'],
    '메뉴': ['피자', '피자', '햄버거', '햄버거', '피자', '햄버거', '햄버거']
}

df = pd.DataFrame(data)
print(df)
print()


# 성별과 메뉴 관계
# 성별과 메뉴 간의 관계를 정리한 크로스탭 만들기
table = pd.crosstab(df['성별'], df['메뉴'])

print(table)
print()


# 메뉴와 성별 관계 순서 바꾸기
# 메뉴를 가로줄에, 성별을 세로줄에 놓고 다시 크로스탭 만들기
table2 = pd.crosstab(df['메뉴'], df['성별'])

print(table2)
print()


# 합계 표시하기
# 합계를 추가한 크로스탭 만들기 (margins=True는 합계를 표시해 준다.)
table3 = pd.crosstab(df['성별'], df['메뉴'], margins=True)

print(table3)
print()


# 성별에 따른 메뉴 선호도 퍼센트로 보기
# 크로스탭에서 각 메뉴 선택의 비율(퍼센트)을 계산하기
table_percent = pd.crosstab(df['성별'], df['메뉴'], normalize=True) * 100
# normalize=True는 비율로 바꿔준다.

table_percent = table_percent.round(2)

print(table_percent)
print()


# 합계와 퍼센트를 모두 함께 표시하기
# 성별-메뉴 크로스탭에 합계(All)를 표시하고 퍼센트로 나타내기
table_percent_all = pd.crosstab(df['성별'], df['메뉴'], margins=True, normalize='all') * 100
table_percent_all = table_percent_all.round(2)

print(table_percent_all)

   성별   메뉴
0  남자   피자
1  여자   피자
2  남자  햄버거
3  여자  햄버거
4  남자   피자
5  여자  햄버거
6  남자  햄버거

메뉴  피자  햄버거
성별
남자   2    2
여자   1    2

성별   남자  여자
메뉴
피자    2   1
햄버거   2   2

메뉴   피자  햄버거  All
성별
남자    2    2    4
여자    1    2    3
All   3    4    7

메뉴     피자    햄버거
성별
남자  28.57  28.57
여자  14.29  28.57

메뉴      피자    햄버거     All
성별
남자   28.57  28.57   57.14
여자   14.29  28.57   42.86
All  42.86  57.14  100.00

## 데이터로 살펴보는 결함 분석

### 결함 패턴 분석

- 반도체 제조 과정에서 발생하는 결함은 제품 품질과 수율에 직접적인 영향을 미친다.
- 결함 패턴 분석을 통해 결함이 가장 많이 발생하는 특정 시간대나 결함이 많이 발생하는 요소를 파악하면 이점이 있음.
    - 1. 공정 제어 및 최적화
    - 2. 예방적 유지보수
    - 3. 비용 절감 및 품질 향상


### 결함이 가장 많은 웨이퍼 10개의 원인 찾기

#### 분석 개요

1. 결함이 없는 데이터 (정상 웨이퍼):
정상적으로 제조된 웨이퍼 700개의 데이터를 분석했습니다. 웨이퍼가 어떤 조건에서 생산됐는지 특징을 살펴보았습니다.

2. 결함이 있는 데이터 (불량 웨이퍼):
결함이 발생한 웨이퍼 300개의 데이터를 분석했습니다. 어떤 조건에서 결함(균열, 핀홀, 입자)이 생겼는지 특징을 파악했습니다.

3. 결함이 가장 많은 데이터 10개 (심각한 불량 웨이퍼):
특별히 결함이 심각한 상위 10개의 웨이퍼를 집중적으로 분석했습니다. 왜 다른 웨이퍼들보다 결함이 많았는지 구체적인 원인은 찾아 봤습니다.

#### 분석 이유
- 불량의 원인 파악
- 품질 관리 개선
- 생산 효율성 증대

#### 기대 효과
- 불량률 감소
- 제조 비용 절감
- 품질 향상

In [3]:
import pandas as pd

oxide_df = pd.read_csv("02_oxide.csv")

# defect_count 값이 0인 데이터만 필터링 (즉, 결함이 없는 웨이퍼만 선택)
no_defect_df = oxide_df[oxide_df['defect_count'] == 0]

# 결함이 없는 행의 통계 분석
no_defect_df.describe()

# defect_count 값이 0보다 큰 데이터만 필터링(즉, 결함이 있는 웨이퍼만 선택)
defect_df = oxide_df[oxide_df['defect_count'] > 0]

# 결함이 있는 행의 통계 분석
defect_df.describe()

# defect_count 값이 많은 순서대로 정렬
defect_df = defect_df.sort_values(by='defect_count', ascending=False)

# 상위 10개 데이터 high_defect_df 대입
high_defect_df = defect_df.head(10)

# 결함이 높은 10개 행의 통계 분석
high_defect_df.describe()

,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2.900000,1013.984921,47.789725,0.620531,3066.565022,337.640574,2.764477,4.500000
std,1.523884,91.323595,27.526094,0.247834,1157.318442,80.050682,1.903893,0.707107
min,1.000000,826.428505,6.432315,0.324976,1211.303576,179.629674,0.182716,4.000000
25%,2.000000,961.223611,31.973725,0.427128,2243.875542,291.426137,1.152141,4.000000
50%,2.500000,1041.735919,37.664467,0.523112,3077.857038,336.743879,2.451553,4.000000
75%,4.000000,1077.247921,67.313839,0.861380,3983.626380,404.774336,4.523382,5.000000
max,5.000000,1120.502432,95.790972,0.998914,4648.832947,438.501878,5.122393,6.000000

#### 결론 (결함 원인 분석)
- 너무 높은 산화 온도와 산화 온도의 급격한 변화가 가장 큰 원인으로 지목됨.

#### 결론 및 효과
- 정상적인 웨이퍼는 약 **998도 근처의 온도에서 안정적으로 생산**되고 있는 반면, 온도가 조금 더 높아지거나 급격하게 변화할 경우 결함 발생 가능성이 높아진다는 사실을 확인할 수 있습니다.

### 시간대별 결함 분석
- 웨이퍼 제조 데이터를 시간대별로 구분하여 오전(6시~12시), 오후(12시~18시), 밤(18시~06시)으로 나누었습니다.
- 각 시간대별로 웨이퍼에 발생한 결함 유형(Crack, Particle, Pinhole)의 개수를 분석하여 어떤 시간대에 어떤 결함이 많이 발생하는지 확인했습니다.

#### 분석 이유
- 시간대별 품질 관리
- 공정 관리 효율성
- 작업자 및 장비 관리 개선

In [4]:
import pandas as pd

oxide_df = pd.read_csv("02_oxide.csv")

# process_date(날짜) + process_time(시간)을 합쳐서 process_datetime컬럼 생성
# pd.to_datetime() -> 데이터를 날짜-시간(datetime) 형식으로 변환
oxide_df['process_datetime'] = pd.to_datetime(oxide_df['process_date'] + ' ' + oxide_df['process_time'])

# 하루를 오전(Morning), 오후(Afternoon), 밤(Night)으로 나누는 함수
def get_time_of_day(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Night'
    
# 각 데이터에 시간대 정보 추가 (오전, 오후, 밤)
# dt.hour -> process_datetime에서 시간(hour)만 추출
# .apply(get_time_of_day) -> 추출한 시간을 get_time_of_day() 함수로 변환해 오전, 오후, 밤을 분류
oxide_df['time_of_day'] = oxide_df['process_datetime'].dt.hour.apply(get_time_of_day)

# 결함이 있는 데이터만 선택 (결함 유형이 'none'인 데이터는 제외)
defect_df = oxide_df[oxide_df['defect_type'] != 'none']

# 시간대별로 결함 유형별 결함 수를 피벗 테이블을 이용해 정리
time_defect_analysis = pd.pivot_table(
    defect_df,
    index='time_of_day',
    columns='defect_type',
    values='defect_count',
    aggfunc='sum',
    fill_value=0  # 데이터가 없을 때 0으로 채움
)

time_defect_analysis

defect_type  crack  particle  pinhole
time_of_day
Afternoon       53        32       58
Morning         38        32       37
Night          108        72       74

#### 분석 결과에 대한 해석
- **밤(Night)** 시간대에 모든 결함 유형(Crack, Particle, Pinhole)이 가장 많이 발생함.
- 특히 **Crack(균열)** 유형 결함은 밤에 월등히 많음.
    - 현장에서 가장 빈번히 지적되는 Crack의 원인은 급격한 온도 변화로 웨이퍼 내부에서 불균일한 팽창 및 수축이 발생하여 균열이 생긴 것으로 알려져 있습니다.
    - 이는 야간의 온도 변화 또는 장비 상태가 가장 큰 원인으로 작용했을 가능성이 있습니다.
- 오전과 오후의 결함 수는 밤보다 상대적으로 낮으며 비교적 균일한 수준을 유지하고 있습니다.

---
#### 결함 발생 원인 및 개선 방안
- **밤(Night)**: 설비의 누적된 피로, 유지보수 미흡, 온습도 변화 등 관리가 취약해질 수 있는 시간대로, 이에 대한 설비 유지보수 및 관리를 강화하는 것이 중요.
- **오후(Afternoon)**: 상대적으로 Pinhole 결함이 많아 압력이나 균일성 관리에 좀 더 신경 써야 함.
- **오전(Morning)**: 결함이 가장 적게 발생했지만, 지속적인 모니터링을 유지하여 공정 안정성을 유지하는 것이 좋음.

##### 개선 방안 제안
- 야간(밤) 공정 중 설비 유지보수 및 점검 빈도를 높이고, 작업자의 피로 관리 및 교대 근무를 최적화할 필요가 있음.
- 균열(Crack)이 많으므로 야간 시간대에는 산화 온도 변화를 더 세밀히 관리해야 함.

## 증착 공정 데이터 구성

### 반도체 8대 공정

1. 웨이퍼 제조 공정 (Wafer 제조)
2. 산화 공정 (Oxidation)
3. 포토 공정 (Photolithography)
4. 식각 공정 (Etching)
5. 증착/이온 주입 공정 (Deposition/Ion Implantation)
    - 증착 : 필요한 물질을 얇게 덮어주는 과정
    - 이온 주입 : 웨이퍼 내부로 전기를 잘 흐르게 하는 물질을 주입하는 과정
6. 금속 배선 공정 (Metalization)
7. EDS 공정 (Electrical Die Sorting, 전기적 칩 검사)
8. 패키징 공정 (Packaging)

### 증착 공정

반도체 칩을 만들 때 웨이퍼 위에 매우 얇은 막을 고르게 입혀주는 과정

#### 박막 (Thin Film)

증착 공정에서 웨이퍼 위에 형성되는 매우 얇고 균일한 막
- 사람의 머리카락보다 훨씬 더 얇게 만들어지며, 반도체 칩이 정상적으로 작동할 수 있도록 여러 가지 중요한 역할을 함.

### 03_wafer_recipe_1.csv 파일 구성

- 증착 공정에 관한 데이터
- 반도체를 만들 때 사용하는 '레시피'와 그 결과를 기록한 것

#### 데이터 활용 목적

- 각 레시피(가스 양, 온도, 전력, 시간)에 따른 박막 두께와 균일성 분석
- 최적의 증착 조건(레시피)을 찾기 위한 분석
- 웨이퍼 제조 공정의 품질 관리(QC, Quality Control)를 위한 데이터로 활용 가능

#### 데이터의 열 (Columns)

**1) 레시피 관련**
- Recipe_Name : 레시피 이름
- Gas_Si2H6 : 가스 양
- Power : 전력
- Time : 시간

**2) 두께 관련**
- THK_Pos_1 ~ THK_Pos_10 : 위치별 두께
    - 반도체 웨이퍼의 10개 지점에서 측정한 박막 두께

In [2]:
# 03_wafer_recipe_1.csv

# 데이터 읽어오기

import pandas as pd

df = pd.read_csv('03_wafer_receipe_1.csv')

df.head()

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,THK_Pos_6,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10
0,Recipe1,200,300,300,30,3014.9,2995.9,3019.4,3045.7,2993.0,2993.0,3047.4,3023.0,2985.9,3016.3
1,Recipe2,200,300,300,40,3006.1,3006.0,3027.3,2962.6,2968.3,3003.1,2989.6,3029.4,2992.8,2977.6
2,Recipe3,200,300,300,50,3084.0,3033.2,3042.0,2997.3,3023.7,3043.3,3005.5,3051.3,3022.0,3031.2
3,Recipe4,200,300,400,30,2931.9,3005.6,2949.6,2918.3,2974.7,2913.4,2956.3,2891.2,2910.2,2955.9
4,Recipe5,200,300,400,40,2992.2,2975.1,2966.5,2961.0,2925.6,2948.4,2956.2,3001.7,2980.3,2917.1

#### df.info()

- 전체 데이터의 개수 (몇 개의 행이 있는지)
- 열(Column)의 이름과 개수
- 각 열의 데이터 개수
- 데이터의 타입 (자료형)

In [3]:
# 데이터의 전반적인 정보 확인

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Recipe_Name  36 non-null     object
 1   Gas_Si2H6    36 non-null     int64
 2   Power        36 non-null     int64
 3   Temp         36 non-null     int64
 4   Time         36 non-null     int64
 5   THK_Pos_1    36 non-null     float64
 6   THK_Pos_2    36 non-null     float64
 7   THK_Pos_3    36 non-null     float64
 8   THK_Pos_4    36 non-null     float64
 9   THK_Pos_5    36 non-null     float64
 10  THK_Pos_6    36 non-null     float64
 11  THK_Pos_7    36 non-null     float64
 12  THK_Pos_8    36 non-null     float64
 13  THK_Pos_9    36 non-null     float64
 14  THK_Pos_10   36 non-null     float64
dtypes: float64(10), int64(4), object(1)
memory usage: 4.3+ KB

#### df.describe()

- count (데이터 개수)
- mean (평균값)
- std (표준편차)
- 25%, 50%, 75% (백분위수 또는 퍼센트(%))
- min (최소값)
- max (최대값)

In [4]:
# 데이터의 기본적인 통계적 수치 분석

df.describe()

,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,THK_Pos_6,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,250.000000,350.000000,350.000000,40.000000,3032.505556,3037.647222,3037.027778,3033.305556,3032.111111,3034.908333,3036.688889,3033.480556,3035.330556,3035.227778
std,41.403934,50.709255,50.709255,8.280787,45.973557,48.909318,51.031909,54.970480,48.420791,49.363922,52.442904,46.320867,53.933000,54.574283
min,200.000000,300.000000,300.000000,30.000000,2931.900000,2963.700000,2939.500000,2918.300000,2925.600000,2913.400000,2954.400000,2891.200000,2910.200000,2917.100000
25%,200.000000,300.000000,300.000000,30.000000,2999.425000,2999.600000,3015.625000,2997.225000,2997.350000,3002.675000,2999.425000,3010.050000,2999.750000,2998.775000
50%,250.000000,350.000000,350.000000,40.000000,3037.200000,3033.200000,3030.900000,3031.250000,3037.450000,3041.400000,3035.350000,3035.850000,3029.700000,3024.000000
75%,300.000000,400.000000,400.000000,50.000000,3064.750000,3071.900000,3069.200000,3077.025000,3062.300000,3066.925000,3056.725000,3067.075000,3085.225000,3079.975000
max,300.000000,400.000000,400.000000,50.000000,3121.500000,3128.900000,3163.700000,3151.400000,3119.600000,3106.500000,3169.000000,3131.900000,3133.000000,3137.800000

### 증착 공정 통계 분석

#### 목표 값

- 증착 공정을 진행할 때는 반드시 원하는 두께나 성질을 나타내는 특정 값을 정하게 됨.
- 증착 공정에서는 대표적으로 막의 두께나 전기적 특성(저항, 전도도 등) 같은 요소들을 목표 값으로 설정함.

#### 통계적 특성 분석

**분석 주요 용어 및 의미**
1) 평균 두께 (Mean Thickness)
2) 최대 두께 (Max Thickness)
3) 최소 두께 (Min Thickness)
4) 표준편차 (Std Thickness)
5) 균일도 (Uniformity, %)
6) 증착률 (Deposition Rate)

#### 레시피 별 박막 두께 분석
#### 레시피별 통계값과 활용법

- 평균 두께 : 각 레시피로 만든 박막의 평균적인 두께
- 최대 두께 : 각 레시피에서 측정된 가장 두꺼운 지점의 두께
- 최소 두께 : 각 레시피에서 측정된 가장 얇은 지점의 두께
- 표준편차 : 각 레시피로 만든 박막 두께가 얼마나 일정한지 나타내는 값. 작을수록 일정한 두께를 유지함.

**이러한 통계값들을 종합하면:**
품질 향상, 불량률 감소, 공정 최적화 !

### Unif(균일도)

**"두께의 일정함"** 을 수치로 나타낸 것

#### Unif(균일도)의 공식

$\text{Unif}(\%) = \frac{\text{최대값} - \text{최소값}}{2 \times \text{평균값}} \times 100$ 

- 가장 두꺼운 부분과 가장 얇은 부분의 차이를 평균 두께로 나누어 얼마나 일정한 두께로 유지되는지 숫자로 나타낸 것.


**최대-최소값 균일성** (Range-based Uniformity) :
- 전체 측정값에서 최대값과 최소값의 차이를 평균값의 2배로 나누어 계산한 균일성 지표

$$
\frac{\text{Max} - \text{Min}}{2 \times \text{Mean}} \times 100 \%
$$

- 측정값 전체의 범위를 강조
- 최대값과 최소값만 사용하여 계산하므로 극단저인 값(이상치)에 민감
- 전체 데이터의 분포나 편차는 고려하지 않음.
- 직관적이며, 현장에서 쉽게 사용 가능

**1-Sigma 균일성** (Sigma-based Uniformity) :
- 측정값의 통계적 분포를 나타내는 표준편차(1σ)

$$
\frac{\sigma}{\text{Mean}} \times 100 \%
$$

- 측정값의 분포를 통계적으로 평가하여 데이터가 평균값 주변에 얼마나 모여 있는지 확인함.
- 전체 데이터의 분포와 편차를 고려하기 때문에 이상치의 영향이 덜함.
- 더 많은 데이터를 활용하여 전체 분포의 품질을 나타냄.
- 통계적인 접근이므로 공정의 품질 관리(QC)나 분석에 자주 사용됨.


##### 자유도

- 마음대로 정할 수 있는 숫자의 개수
- 통계에서의 자유도)
    - 평균을 먼저 계산하면 데이터 하나는 자동으로 결정됨.
    - 평균이 정해져 있기 때문에, 마지막 숫자는 자유롭게 정할 수 없게 됨. -> 이미 평균으로 결정되어 버린..
    - 그래서 표준편차를 계산할 때는 (데이터 개수 - 1)로 나눠주는 거야.

### Deposition Rate (증착률)

- 웨이퍼 위에 물질이 쌓이는 속도 = 단위 시간당 박막이 증착되는 두께

#### Deposition Rate가 중요한 이유

- Deposition Rate가 높으면 물질이 빠르게 쌓여 효율적인 생산이 가능하지만, 너무 빠르면 두께가 불균일해질 수 있음.
- 반대로 Deposition Rate가 너무 낮으면 공정 시간이 길어져 생산성이 낮아질 수 있음.

- 최적의 증착률을 유지하는 것이 아주 중요
    - 반도체의 품질도 좋고 생산 효율도 좋은 가장 이상적인 속도


#### Deposition Rate 계산 방법

$$
\text{Deposition Rate} \, (\text{nm}/\text{s}) = \frac{\text{Average Thickness} \, (\text{nm})}{\text{Deposition Time} \, (\text{s})}
$$


#### 반도체 공정에서 증착률 활용 방법

1) 품질 관리 및 균일도 조절
2) 생산성 관리 및 비용 절감
3) 제조 공정의 최적화 및 기준 설정

In [5]:
# 파이썬을 이용한 통계적 특성 분석

import pandas as pd

df = pd.read_csv('03_wafer_receipe_1.csv')

df.head()

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,THK_Pos_6,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10
0,Recipe1,200,300,300,30,3014.9,2995.9,3019.4,3045.7,2993.0,2993.0,3047.4,3023.0,2985.9,3016.3
1,Recipe2,200,300,300,40,3006.1,3006.0,3027.3,2962.6,2968.3,3003.1,2989.6,3029.4,2992.8,2977.6
2,Recipe3,200,300,300,50,3084.0,3033.2,3042.0,2997.3,3023.7,3043.3,3005.5,3051.3,3022.0,3031.2
3,Recipe4,200,300,400,30,2931.9,3005.6,2949.6,2918.3,2974.7,2913.4,2956.3,2891.2,2910.2,2955.9
4,Recipe5,200,300,400,40,2992.2,2975.1,2966.5,2961.0,2925.6,2948.4,2956.2,3001.7,2980.3,2917.1

In [6]:
# df에서 박막 두께를 측정한 열만 선택해서 저장

thickness_df = df.loc[:, "THK_Pos_1":"THK_Pos_10"]

thickness_df.head()

,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,THK_Pos_6,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10
0,3014.9,2995.9,3019.4,3045.7,2993.0,2993.0,3047.4,3023.0,2985.9,3016.3
1,3006.1,3006.0,3027.3,2962.6,2968.3,3003.1,2989.6,3029.4,2992.8,2977.6
2,3084.0,3033.2,3042.0,2997.3,3023.7,3043.3,3005.5,3051.3,3022.0,3031.2
3,2931.9,3005.6,2949.6,2918.3,2974.7,2913.4,2956.3,2891.2,2910.2,2955.9
4,2992.2,2975.1,2966.5,2961.0,2925.6,2948.4,2956.2,3001.7,2980.3,2917.1

In [13]:
# thickness_df에 있는 10개의 박막 두께를 행 별로 평균을 내서 Mean_Thickness라는 새로운 열을 만들어서 추가
# axis=1은 가로 방향(행 방향)으로 계산한다는 뜻
df['Mean_Thickness'] = thickness_df.mean(axis=1)

# 최대값은 Max_Thickness 열로 만들어서 추가
df['Max_Thickness'] = thickness_df.max(axis=1)

# 최소값은 Min_Thickness 열로 만들어서 추가
df['Min_Thickness'] = thickness_df.min(axis=1)

# 표준편차를 Std_Thickness 열로 만들어서 추가
df['Std_Thickness'] = thickness_df.std(axis=1)

# 균일도 계산하여 Unif 열로 만들어서 추가
# 균일도 = (최대 두께 - 최소 두께) / (2 x 평균 두께) x 100
df['Unif'] = (df['Max_Thickness'] - df['Min_Thickness']) / (2 * df['Mean_Thickness']) * 100

# Deposition Rate를 계산하여 열 추가
# Deposition Rate = Mean_Thickness / Time
df['Deposition_Rate'] = df['Mean_Thickness'] / df['Time']


df.head()

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10,Mean_Thickness,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate
0,Recipe1,200,300,300,30,3014.9,2995.9,3019.4,3045.7,2993.0,...,3047.4,3023.0,2985.9,3016.3,3013.45,3047.4,2985.9,21.686926,1.020425,100.448333
1,Recipe2,200,300,300,40,3006.1,3006.0,3027.3,2962.6,2968.3,...,2989.6,3029.4,2992.8,2977.6,2996.28,3029.4,2962.6,22.655625,1.114716,74.907000
2,Recipe3,200,300,300,50,3084.0,3033.2,3042.0,2997.3,3023.7,...,3005.5,3051.3,3022.0,3031.2,3033.35,3084.0,2997.3,24.411439,1.429113,60.667000
3,Recipe4,200,300,400,30,2931.9,3005.6,2949.6,2918.3,2974.7,...,2956.3,2891.2,2910.2,2955.9,2940.71,3005.6,2891.2,34.361815,1.945108,98.023667
4,Recipe5,200,300,400,40,2992.2,2975.1,2966.5,2961.0,2925.6,...,2956.2,3001.7,2980.3,2917.1,2962.41,3001.7,2917.1,27.026261,1.427891,74.060250

In [14]:
# 새롭게 계산된 데이터를 csv 파일 형태로 저장
# index=False : 데이터 저장 시 별도의 행 번호를 저장하지 않음.
# encoding='utf-8-sig' : 파일의 한글이나 특수 문자가 깨지지 않도록 안전하게 저장하기 위한 옵션

df.to_csv('03_wafer_receipe_2.csv', index=False, encoding='utf-8-sig')

### 최적 증착 공정 레시피 탐색

#### 최적의 레시피

반도체 제조 공정에서 목표하는 특성(두께, 균일성)을 가장 효율적으로 달성할 수 있는 공정 변수들의 조합
- 이상적인 레시피는 제품 품질을 극대화하면서 동시에 생산 비용과 시간을 최소화함.

- 원하는 품질을 정확히 만족하면서 효율적이고 경제적인 제조 조건을 찾는 것을 **"최적의 레시피를 찾는다"** 라고 표현함.

#### 최적의 레시피를 찾는 과정

1. 목표 품질 기준 설정
2. 다양한 레시피로 실험 진행
3. 실험 결과 분석
4. 최적의 레시피 선정

**최적의 레시피 선정 효과**
- 제품 품질 향상
- 비용 절감 및 효율성 증가
- 경쟁력 강화

### 최적의 레시피 탐색

증착 공정에서 박막 두께의 목표값이 3100nm이고 허용 범위가 3000 ~ 3200nm일 때, 이 조건을 만족하는 최적의 레시피를 찾아보자.

1. 목표 설정 (목표값과 범위)
- 측정한 10개 지점의 두께가 **정확히 3100nm**인 반도체 박막을 만들고 싶음.
- 약간의 오차 포함 **3000 ~ 3200nm**를 허용 범위로 정함.

2. 여러 레시피로 실험하기
- 사용하는 가스 양 (Gas_Si2H6)
- 공정에서 사용하는 전력 (Power)
- 공정 시 온도 (Temperature)
- 공정 시간 (Time)

3. 조건에 맞는 레시피 추려내기
- 박막의 가장 얇은 부분(최소값) $\ge$ 3000nm
- 박막의 가장 두꺼운 부분(최대값) $\le$ 3200nm

4. 가장 좋은 레시피의 조건 선택하기
- 목표값에 얼마나 가까운가?
- 균일성이 얼마나 뛰어난가?
- 표본 표준편차가 얼마나 낮은가?
- 증착률이 높은가?

1) 두께 점수 계산
2) 균일성 점수 계산
3) 표준편차 점수 계산
4) 증착 속도 점수 계산

5. 최종 점수 계산
- 네 가지 점수에 각각의 가중치를 곱해 최종 점수를 계산

```scss
최종 점수 = (0.4 x 두께 점수) + (0.2 x 균일성 점수) + (0.2 x 표준편차 점수) + (0.2 x 증착 속도 점수)
```

- 최종 점수가 가장 높은 레시피가 **최적의 레시피 !**

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

df = pd.read_csv('03_wafer_receipe_2.csv')

df.head()

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10,Mean_Thickness,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate
0,Recipe1,200,300,300,30,3014.9,2995.9,3019.4,3045.7,2993.0,...,3047.4,3023.0,2985.9,3016.3,3013.45,3047.4,2985.9,21.686926,1.020425,100.448333
1,Recipe2,200,300,300,40,3006.1,3006.0,3027.3,2962.6,2968.3,...,2989.6,3029.4,2992.8,2977.6,2996.28,3029.4,2962.6,22.655625,1.114716,74.907000
2,Recipe3,200,300,300,50,3084.0,3033.2,3042.0,2997.3,3023.7,...,3005.5,3051.3,3022.0,3031.2,3033.35,3084.0,2997.3,24.411439,1.429113,60.667000
3,Recipe4,200,300,400,30,2931.9,3005.6,2949.6,2918.3,2974.7,...,2956.3,2891.2,2910.2,2955.9,2940.71,3005.6,2891.2,34.361815,1.945108,98.023667
4,Recipe5,200,300,400,40,2992.2,2975.1,2966.5,2961.0,2925.6,...,2956.2,3001.7,2980.3,2917.1,2962.41,3001.7,2917.1,27.026261,1.427891,74.060250

In [ ]:
# 목표로 하는 박막의 두께 = 3100nm
target_thickness = 3100

# 허용 오차 (± 100nm)
tolerance = 100

# 여러 레시피 중 목표 범위(3100 ± 100nm)에 들어가는 레시피만 뽑아내자.

# 데이터 프레임 조건 탐색
# 최소 두께가 3000 이상 최대 두께가 3200 이하인 조건을 이용해 필터링

filtered_recipes = df[
    (df['Min_Thickness'] >= target_thickness - tolerance) &  # 최소 두께가 3000nm 이상이고
    (df['Max_Thickness'] <= target_thickness + tolerance)    # 최대 두께가 3200nm이하인 조건.
].copy()  # 데이터를 안전하게 독립적으로 관리할 수 있도록 복사본 만들기 (원본 훼손 방지)

filtered_recipes

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,THK_Pos_7,THK_Pos_8,THK_Pos_9,THK_Pos_10,Mean_Thickness,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate
8,Recipe9,200,400,300,50,3036.7,3045.4,3062.2,3032.2,3027.9,...,3053.7,3044.9,3032.1,3047.7,3041.53,3062.2,3027.9,11.087435,0.563861,60.830600
13,Recipe14,250,300,300,40,3013.5,3062.1,3028.1,3074.2,3032.4,...,3036.5,3050.3,3084.4,3023.1,3051.11,3106.5,3013.5,30.042394,1.524036,76.277750
14,Recipe15,250,300,300,50,3086.8,3119.2,3031.8,3085.5,3087.8,...,3042.9,3040.4,3095.7,3088.9,3078.25,3119.2,3031.8,29.418635,1.419638,61.565000
17,Recipe18,250,300,400,50,3003.3,3005.5,3027.7,3040.2,3038.3,...,3030.4,3073.6,3022.1,3111.6,3040.75,3111.6,3003.3,32.613673,1.780811,60.815000
18,Recipe19,250,400,300,30,3049.4,3027.1,3023.9,3047.2,3036.6,...,3047.1,3038.9,3027.3,3017.3,3036.55,3050.7,3017.3,12.023334,0.549966,101.218333
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3046.7,3062.3,3060.9,3042.9,3057.18,3072.8,3041.3,10.566909,0.515181,76.429500
20,Recipe21,250,400,300,50,3085.4,3088.4,3096.2,3095.8,3059.3,...,3087.7,3087.7,3087.7,3137.8,3089.19,3137.8,3059.3,20.851989,1.270560,61.783800
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3065.8,3060.4,3133.0,3092.1,3079.92,3133.0,3044.0,26.706545,1.444843,102.664000
25,Recipe26,300,300,300,40,3062.2,3127.5,3163.7,3131.0,3054.4,...,3138.0,3078.8,3113.3,3123.2,3107.76,3163.7,3054.4,35.745682,1.758501,77.694000
26,Recipe27,300,300,300,50,3092.2,3118.2,3022.8,3089.3,3112.4,...,3169.0,3077.1,3106.8,3123.9,3099.43,3169.0,3022.8,37.745553,2.358498,61.988600
29,Recipe30,300,300,400,50,3063.8,3055.2,3052.3,3095.5,3080.7,...,3097.0,3079.2,3094.4,3088.9,3075.62,3097.0,3049.2,18.910655,0.777079,61.512400
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3071.1,3088.2,3077.0,3081.66,3099.2,3067.6,10.188577,0.512711,102.722000
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3110.2,3095.3,3104.9,3098.0,3106.61,3119.6,3095.3,8.738224,0.391102,77.665250
32,Recipe33,300,400,300,50,3121.5,3128.9,3107.7,3151.4,3104.9,...,3137.4,3131.9,3129.4,3129.4,3124.43,3151.4,3101.8,15.644669,0.793745,62.488600
33,Recipe34,300,400,400,30,3029.8,3016.5,3031.1,3019.8,3044.6,...,3017.6,3025.2,3036.2,3021.5,3027.01,3044.6,3016.5,8.842002,0.464154,100.900333
34,Recipe35,300,400,400,40,3037.7,3053.7,3053.7,3042.4,3042.9,...,3028.3,3028.9,3039.2,3046.8,3042.71,3053.7,3028.3,9.490516,0.417391,76.067750
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3069.7,3065.7,3074.8,3057.6,3070.98,3092.1,3055.0,11.022885,0.604042,61.419600

In [47]:
# 목표 두께와 각 레시피 평균 두께와의 차이 중 가장 큰 값 찾기
# abs() : 절대값 반환

max_thickness_diff = abs(filtered_recipes['Mean_Thickness'] - 3100).max()

print(f"(평균 두께-목표두께) 중 가장 큰 값: {max_thickness_diff}")


# 각 레시피가 목표 두께에 얼마나 가까운지 평가하는 점수 계산
# 목표에 가까울수록 점수가 1에 가까움.
# 두께 점수 = 1 - ((|평균두께 - 목표두께|) / 모든 레시피 중 목표와 가장 큰 두께 차이)

filtered_recipes['Score_Thickness'] = 1 - (abs(filtered_recipes['Mean_Thickness'] - 3100) / max_thickness_diff)

filtered_recipes.head()

(평균 두께-목표두께) 중 가장 큰 값: 72.98999999999978

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate,Score_Thickness,Score_Unif,Score_Std,Score_Deposition,Final_Score
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3067.6,10.188577,0.512711,102.72200,0.748733,0.938188,0.950000,1.000000,0.877131
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3119.6,3095.3,8.738224,0.391102,77.66525,0.909440,1.000000,1.000000,0.402087,0.844193
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3133.0,3044.0,26.706545,1.444843,102.66400,0.724894,0.464398,0.380559,0.998616,0.658672
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3072.8,3041.3,10.566909,0.515181,76.42950,0.413344,0.936932,0.936958,0.372599,0.614636
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3092.1,3055.0,11.022885,0.604042,61.41960,0.602411,0.891766,0.921238,0.014427,0.606451

In [44]:
# 균일성의 최대값과 최소값의 차이

max_unif_diff = filtered_recipes['Unif'].max() - filtered_recipes['Unif'].min()

print(f"가장 나쁜 균일성 값: {filtered_recipes['Unif'].max():.2f}")
print(f"가장 좋은 균일성 값: {filtered_recipes['Unif'].min():.2f}")
print(f"가장 나쁜 균일성 값-가장 좋은 균일성 값: {max_unif_diff}")


# 균일성 점수 계산
# 균일성이 좋을수록(값이 작을수록) 점수가 1에 가까움.
# 균일성 점수 = 1 - ((해당 레시피 균일성 값 - 가장 좋은 균일성 값) / (가장 나쁜 균일성 값 - 가장 좋은 균일성 값))

filtered_recipes['Score_Unif'] = 1 - ((filtered_recipes['Unif'] - filtered_recipes['Unif'].min()) / max_unif_diff)

filtered_recipes.head()

가장 나쁜 균일성 값: 2.36
가장 좋은 균일성 값: 0.39
가장 나쁜 균일성 값-가장 좋은 균일성 값: 1.9673966210434806

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate,Score_Thickness,Score_Unif,Score_Std,Score_Deposition,Final_Score
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3067.6,10.188577,0.512711,102.72200,0.748733,0.938188,0.950000,1.000000,0.877131
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3119.6,3095.3,8.738224,0.391102,77.66525,0.909440,1.000000,1.000000,0.402087,0.844193
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3133.0,3044.0,26.706545,1.444843,102.66400,0.724894,0.464398,0.380559,0.998616,0.658672
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3072.8,3041.3,10.566909,0.515181,76.42950,0.413344,0.936932,0.936958,0.372599,0.614636
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3092.1,3055.0,11.022885,0.604042,61.41960,0.602411,0.891766,0.921238,0.014427,0.606451

In [42]:
# 박막 두께의 표준편차의 최대값과 최소값 차이 구하기

max_std_diff = filtered_recipes['Std_Thickness'].max() - filtered_recipes['Std_Thickness'].min()

print(f"가장 높은 표준편차: {filtered_recipes['Std_Thickness'].max():.2f}")
print(f"가장 낮은 표준편차: {filtered_recipes['Std_Thickness'].min():.2f}")
print(f"가장 높은 표준편차-가장 낮은 표준편차: {max_std_diff}")


# 표준편차 점수 계산
# 표준편차가 작을수록(박막이 균일할수록) 점수가 1에 가까움.
# 표준편차 점수 = 1 - ((해당 레시피 표준편차 값 - 가장 낮은 표준편차) / (가장 높은 표준편차 - 가장 낮은 표준편차))

filtered_recipes['Score_Std'] = 1 - ((filtered_recipes['Std_Thickness'] - filtered_recipes['Std_Thickness'].min()) / max_std_diff)

filtered_recipes.head()

가장 높은 표준편차: 37.75
가장 낮은 표준편차: 8.74
가장 높은 표준편차-가장 낮은 표준편차: 29.007329264576015

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate,Score_Thickness,Score_Unif,Score_Std,Score_Deposition,Final_Score
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3067.6,10.188577,0.512711,102.72200,0.748733,0.938188,0.950000,1.000000,0.877131
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3119.6,3095.3,8.738224,0.391102,77.66525,0.909440,1.000000,1.000000,0.402087,0.844193
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3133.0,3044.0,26.706545,1.444843,102.66400,0.724894,0.464398,0.380559,0.998616,0.658672
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3072.8,3041.3,10.566909,0.515181,76.42950,0.413344,0.936932,0.936958,0.372599,0.614636
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3092.1,3055.0,11.022885,0.604042,61.41960,0.602411,0.891766,0.921238,0.014427,0.606451

In [48]:
# 증착속도의 최대값과 최소값 차이 구하기

max_deposition_diff = filtered_recipes['Deposition_Rate'].max() - filtered_recipes['Deposition_Rate'].min()

print(f"가장 높은 속도: {filtered_recipes['Deposition_Rate'].max():.2f}")
print(f"가장 낮은 속도: {filtered_recipes['Deposition_Rate'].min():.2f}")
print(f"가장 높은 속도-가장 낮은 속도: {max_deposition_diff}")


# 증착속도 점수 계산
# 증착속도가 빠를수록 점수가 1에 가까움.
# 증착속도 점수 = (해당 레시피 속도 - 가장 낮은 속도) / (가장 높은 속도 - 가장 낮은 속도)

filtered_recipes['Score_Deposition'] = (filtered_recipes['Deposition_Rate'] - filtered_recipes['Deposition_Rate'].min()) / max_deposition_diff

filtered_recipes.head()

가장 높은 속도: 102.72
가장 낮은 속도: 60.81
가장 높은 속도-가장 낮은 속도: 41.907000000000004

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate,Score_Thickness,Score_Unif,Score_Std,Score_Deposition,Final_Score
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3067.6,10.188577,0.512711,102.72200,0.748733,0.938188,0.950000,1.000000,0.877131
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3119.6,3095.3,8.738224,0.391102,77.66525,0.909440,1.000000,1.000000,0.402087,0.844193
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3133.0,3044.0,26.706545,1.444843,102.66400,0.724894,0.464398,0.380559,0.998616,0.658672
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3072.8,3041.3,10.566909,0.515181,76.42950,0.413344,0.936932,0.936958,0.372599,0.614636
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3092.1,3055.0,11.022885,0.604042,61.41960,0.602411,0.891766,0.921238,0.014427,0.606451

In [26]:
# 평가 지표별로 중요도(가중치) 설정

weight_thickness = 0.4  # 두께가 목표값과 가까운 것이 가장 중요 (40%)
weight_unif = 0.2  # 균일성 중요도 (20%)
weight_std = 0.2  # 두께 표준편차의 중요도 (20%)
weight_deposition = 0.2  # 증착속도 중요도 (20%)


# 최종 점수를 계산하여 'Final_Score' 열에 저장
filtered_recipes['Final_Score'] = (
    filtered_recipes['Score_Thickness'] * weight_thickness +
    filtered_recipes['Score_Unif'] * weight_unif +
    filtered_recipes['Score_Std'] * weight_std +
    filtered_recipes['Score_Deposition'] * weight_deposition
)


# 최종 점수로 정렬하여 최적의 레시피 찾기
filtered_recipes = filtered_recipes.sort_values(by='Final_Score', ascending=False)

filtered_recipes.head()

,Recipe_Name,Gas_Si2H6,Power,Temp,Time,THK_Pos_1,THK_Pos_2,THK_Pos_3,THK_Pos_4,THK_Pos_5,...,Max_Thickness,Min_Thickness,Std_Thickness,Unif,Deposition_Rate,Score_Thickness,Score_Unif,Score_Std,Score_Deposition,Final_Score
30,Recipe31,300,400,300,30,3067.6,3071.6,3091.2,3089.2,3079.7,...,3099.2,3067.6,10.188577,0.512711,102.72200,0.748733,0.938188,0.950000,1.000000,0.877131
31,Recipe32,300,400,300,40,3096.7,3116.5,3112.4,3112.2,3119.6,...,3119.6,3095.3,8.738224,0.391102,77.66525,0.909440,1.000000,1.000000,0.402087,0.844193
24,Recipe25,300,300,300,30,3056.2,3076.6,3095.1,3106.0,3044.0,...,3133.0,3044.0,26.706545,1.444843,102.66400,0.724894,0.464398,0.380559,0.998616,0.658672
19,Recipe20,250,400,300,40,3053.3,3072.8,3063.2,3041.3,3062.6,...,3072.8,3041.3,10.566909,0.515181,76.42950,0.413344,0.936932,0.936958,0.372599,0.614636
35,Recipe36,300,400,400,50,3074.7,3092.1,3082.9,3067.6,3069.7,...,3092.1,3055.0,11.022885,0.604042,61.41960,0.602411,0.891766,0.921238,0.014427,0.606451

In [52]:
# iloc[0] : 정렬된 데이터에서 가장 첫 번째 행(최고점)을 선택

optimal_recipe = filtered_recipes.iloc[0]

print("✅ 최적의 레시피 정보 ✅")
print(optimal_recipe[['Recipe_Name', 'Mean_Thickness', 'Min_Thickness', 'Max_Thickness', 'Unif', 'Std_Thickness', 'Deposition_Rate', 'Final_Score']])

✅ 최적의 레시피 정보 ✅
Recipe_Name         Recipe31
Mean_Thickness       3081.66
Min_Thickness         3067.6
Max_Thickness         3099.2
Unif                0.512711
Std_Thickness      10.188577
Deposition_Rate      102.722
Final_Score         0.877131
Name: 30, dtype: object