In [2]:
import pandas as pd

oxide_df = pd.read_csv('02_oxide.csv')

oxide_df.head(10)

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type
0,2025-01-01,0:00:00,eq_1,chamber_1,w_0,p-type,3,908.332942,30.450712,0.725458,4007.192654,212.318551,4.158928,0,none
1,2025-01-01,1:00:00,eq_2,chamber_2,w_1,n-type,1,998.595807,43.926035,0.610652,3273.074465,359.152236,3.920767,2,particle
2,2025-01-01,2:00:00,eq_3,chamber_3,w_2,p-type,5,1016.761934,66.715328,0.816619,2098.663479,442.100760,2.428848,1,pinhole
3,2025-01-01,3:00:00,eq_4,chamber_1,w_3,n-type,3,952.625393,46.845448,0.761523,2897.739657,225.153908,0.437444,2,particle
4,2025-01-01,4:00:00,eq_5,chamber_2,w_4,p-type,3,968.690498,52.487699,0.649097,2335.106388,423.234943,2.860362,0,none
5,2025-01-01,5:00:00,eq_1,chamber_3,w_5,p-type,1,1000.768949,9.487946,0.539360,3317.253611,184.257527,2.906109,0,none
6,2025-01-01,6:00:00,eq_2,chamber_1,w_6,p-type,5,1047.754819,72.688192,0.219864,4556.002443,403.046333,2.241902,0,none
7,2025-01-01,7:00:00,eq_3,chamber_2,w_7,p-type,4,948.356539,36.511521,0.335200,3277.219938,231.376232,1.405614,0,none
8,2025-01-01,8:00:00,eq_4,chamber_3,w_8,n-type,5,957.077503,29.957884,0.477190,3526.889673,319.300508,1.817399,1,pinhole
9,2025-01-01,9:00:00,eq_5,chamber_1,w_9,p-type,2,1056.279389,33.138401,0.639369,3074.991388,267.924601,1.670817,0,none

In [3]:
oxide_df['process_datetime'] = pd.to_datetime(oxide_df['process_date'] + ' ' + oxide_df['process_time']) 

oxide_df.head(20)

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
0,2025-01-01,0:00:00,eq_1,chamber_1,w_0,p-type,3,908.332942,30.450712,0.725458,4007.192654,212.318551,4.158928,0,none,2025-01-01 00:00:00
1,2025-01-01,1:00:00,eq_2,chamber_2,w_1,n-type,1,998.595807,43.926035,0.610652,3273.074465,359.152236,3.920767,2,particle,2025-01-01 01:00:00
2,2025-01-01,2:00:00,eq_3,chamber_3,w_2,p-type,5,1016.761934,66.715328,0.816619,2098.663479,442.100760,2.428848,1,pinhole,2025-01-01 02:00:00
3,2025-01-01,3:00:00,eq_4,chamber_1,w_3,n-type,3,952.625393,46.845448,0.761523,2897.739657,225.153908,0.437444,2,particle,2025-01-01 03:00:00
4,2025-01-01,4:00:00,eq_5,chamber_2,w_4,p-type,3,968.690498,52.487699,0.649097,2335.106388,423.234943,2.860362,0,none,2025-01-01 04:00:00
5,2025-01-01,5:00:00,eq_1,chamber_3,w_5,p-type,1,1000.768949,9.487946,0.539360,3317.253611,184.257527,2.906109,0,none,2025-01-01 05:00:00
6,2025-01-01,6:00:00,eq_2,chamber_1,w_6,p-type,5,1047.754819,72.688192,0.219864,4556.002443,403.046333,2.241902,0,none,2025-01-01 06:00:00
7,2025-01-01,7:00:00,eq_3,chamber_2,w_7,p-type,4,948.356539,36.511521,0.335200,3277.219938,231.376232,1.405614,0,none,2025-01-01 07:00:00
8,2025-01-01,8:00:00,eq_4,chamber_3,w_8,n-type,5,957.077503,29.957884,0.477190,3526.889673,319.300508,1.817399,1,pinhole,2025-01-01 08:00:00
9,2025-01-01,9:00:00,eq_5,chamber_1,w_9,p-type,2,1056.279389,33.138401,0.639369,3074.991388,267.924601,1.670817,0,none,2025-01-01 09:00:00
10,2025-01-01,10:00:00,eq_1,chamber_2,w_10,n-type,4,986.351230,6.048735,0.562337,1204.662026,171.899671,0.090345,1,crack,2025-01-01 10:00:00
11,2025-01-01,11:00:00,eq_2,chamber_3,w_11,p-type,3,961.123048,47.014054,0.359366,1931.434228,417.603775,0.055584,3,particle,2025-01-01 11:00:00
12,2025-01-01,12:00:00,eq_3,chamber_1,w_12,p-type,4,1036.434240,38.629434,0.105818,2968.006918,322.491867,3.844729,0,none,2025-01-01 12:00:00
13,2025-01-01,13:00:00,eq_4,chamber_2,w_13,p-type,3,975.590150,8.300796,0.546615,2240.941135,321.379061,1.410403,1,particle,2025-01-01 13:00:00
14,2025-01-01,14:00:00,eq_5,chamber_3,w_14,n-type,3,1051.371077,15.126233,0.357063,1727.054391,356.680356,0.488391,2,crack,2025-01-01 14:00:00
15,2025-01-01,15:00:00,eq_1,chamber_1,w_15,p-type,4,966.813981,45.565687,0.761147,3016.531368,431.688657,3.706283,0,none,2025-01-01 15:00:00
16,2025-01-01,16:00:00,eq_2,chamber_2,w_16,n-type,3,992.020272,-4.192467,0.121552,2291.239174,170.230863,1.455021,0,none,2025-01-01 16:00:00
17,2025-01-01,17:00:00,eq_3,chamber_3,w_17,n-type,3,1047.248583,44.713710,0.626345,2032.430573,344.942926,1.199740,0,none,2025-01-01 17:00:00
18,2025-01-01,18:00:00,eq_4,chamber_1,w_18,n-type,2,988.686956,-1.620361,0.947327,2855.941670,165.290701,2.048441,1,pinhole,2025-01-01 18:00:00
19,2025-01-01,19:00:00,eq_5,chamber_2,w_19,n-type,5,1037.802666,-4.184556,0.256968,1533.137032,305.969505,2.471876,0,none,2025-01-01 19:00:00

In [4]:
oxide_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   process_date           1000 non-null   object
 1   process_time           1000 non-null   object
 2   equipment_id           1000 non-null   object
 3   chamber_id             1000 non-null   object
 4   wafer_id               1000 non-null   object
 5   wafer_doping_type      1000 non-null   object
 6   precleaning_time       1000 non-null   int64
 7   oxidation_temperature  999 non-null    float64
 8   oxidation_time         1000 non-null   float64
 9   pressure               995 non-null    float64
 10  gas_flow_rate          1000 non-null   float64
 11  oxide_thickness        999 non-null    float64
 12  uniformity             989 non-null    float64
 13  defect_count           1000 non-null   int64
 14  defect_type            1000 non-null   object
 15  process_datetime       1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(2), object(7)
memory usage: 125.1+ KB

In [33]:
oxide_df.isna().sum()

process_date              0
process_time              0
equipment_id              0
chamber_id                0
wafer_id                  0
wafer_doping_type         0
precleaning_time          0
oxidation_temperature     1
oxidation_time            0
pressure                  5
gas_flow_rate             0
oxide_thickness           1
uniformity               11
defect_count              0
defect_type               0
process_datetime          0
dtype: int64

In [27]:
from IPython.display import display

a = oxide_df[oxide_df['oxidation_temperature'].isnull()]
b = oxide_df[oxide_df['pressure'].isnull()]
c = oxide_df[oxide_df['oxide_thickness'].isnull()]
d = oxide_df[oxide_df['uniformity'].isnull()]

print("=== oxidation_temperature null값 ===\n")
display(a)
print("=== pressure null값 ===")
display(b)
print("=== oxide_thickness null값 ===")
display(c)
print("=== uniformity null값 ===")
display(d)

=== oxidation_temperature null값 ===

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
68,2025-01-03,20:00:00,eq_4,chamber_3,w_68,n-type,4,NaN,62.42454,0.997254,3556.431388,444.176287,NaN,0,none,2025-01-03 20:00:00

=== pressure null값 ===

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
154,2025-01-07,10:00:00,eq_5,chamber_2,w_154,p-type,4,995.755509,60.396087,NaN,2096.851556,441.923187,3.207975,0,none,2025-01-07 10:00:00
283,2025-01-12,19:00:00,eq_4,chamber_2,w_283,n-type,3,973.263338,36.432768,NaN,1112.486025,430.577447,1.391949,0,none,2025-01-12 19:00:00
370,2025-01-16,10:00:00,eq_1,chamber_2,w_370,n-type,5,1002.188988,29.367653,NaN,3072.061396,277.393404,2.567354,0,none,2025-01-16 10:00:00
668,2025-01-28,20:00:00,eq_4,chamber_3,w_668,n-type,4,1000.068983,-0.764547,NaN,4344.315603,321.447324,3.434626,2,crack,2025-01-28 20:00:00
674,2025-01-29,2:00:00,eq_5,chamber_3,w_674,n-type,4,1020.205083,6.887325,NaN,2955.803706,271.363845,1.669236,1,crack,2025-01-29 02:00:00

=== oxide_thickness null값 ===

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
742,2025-01-31,22:00:00,eq_3,chamber_2,w_742,p-type,2,941.71642,14.627721,0.469658,1697.993946,NaN,3.00632,2,particle,2025-01-31 22:00:00

=== uniformity null값 ===

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
68,2025-01-03,20:00:00,eq_4,chamber_3,w_68,n-type,4,NaN,62.424540,0.997254,3556.431388,444.176287,NaN,0,none,2025-01-03 20:00:00
82,2025-01-04,10:00:00,eq_3,chamber_2,w_82,p-type,2,988.115244,53.168411,0.782236,3585.239735,291.223278,NaN,0,none,2025-01-04 10:00:00
93,2025-01-04,21:00:00,eq_4,chamber_1,w_93,p-type,5,953.185568,7.085068,0.722490,2837.374622,137.169793,NaN,0,none,2025-01-04 21:00:00
149,2025-01-07,5:00:00,eq_5,chamber_3,w_149,n-type,2,1002.068953,39.454770,0.951175,3291.081107,306.645414,NaN,2,crack,2025-01-07 05:00:00
255,2025-01-11,15:00:00,eq_1,chamber_1,w_255,n-type,4,1005.265466,45.736489,0.270888,3697.174295,424.441262,NaN,0,none,2025-01-11 15:00:00
402,2025-01-17,18:00:00,eq_3,chamber_1,w_402,n-type,2,929.979022,45.078655,0.316723,1769.263091,360.610053,NaN,0,none,2025-01-17 18:00:00
502,2025-01-21,22:00:00,eq_3,chamber_2,w_502,p-type,1,1012.591838,5.021486,0.683618,2995.871777,268.052343,NaN,3,crack,2025-01-21 22:00:00
595,2025-01-25,19:00:00,eq_1,chamber_2,w_595,n-type,1,1029.839139,17.349754,0.791872,4038.080595,262.388083,NaN,0,none,2025-01-25 19:00:00
705,2025-01-30,9:00:00,eq_1,chamber_1,w_705,n-type,1,1010.593934,30.090149,0.764691,1973.770467,216.090755,NaN,0,none,2025-01-30 09:00:00
738,2025-01-31,18:00:00,eq_4,chamber_1,w_738,p-type,1,1067.601424,45.982117,0.638027,2560.954198,244.401239,NaN,3,crack,2025-01-31 18:00:00
980,2025-02-10,20:00:00,eq_1,chamber_3,w_980,n-type,5,1086.173267,41.787002,0.381551,4295.585526,287.695763,NaN,0,none,2025-02-10 20:00:00

In [28]:
df1 = oxide_df[oxide_df['defect_type'] == 'none']
df1

,process_date,process_time,equipment_id,chamber_id,wafer_id,wafer_doping_type,precleaning_time,oxidation_temperature,oxidation_time,pressure,gas_flow_rate,oxide_thickness,uniformity,defect_count,defect_type,process_datetime
0,2025-01-01,0:00:00,eq_1,chamber_1,w_0,p-type,3,908.332942,30.450712,0.725458,4007.192654,212.318551,4.158928,0,none,2025-01-01 00:00:00
4,2025-01-01,4:00:00,eq_5,chamber_2,w_4,p-type,3,968.690498,52.487699,0.649097,2335.106388,423.234943,2.860362,0,none,2025-01-01 04:00:00
5,2025-01-01,5:00:00,eq_1,chamber_3,w_5,p-type,1,1000.768949,9.487946,0.539360,3317.253611,184.257527,2.906109,0,none,2025-01-01 05:00:00
6,2025-01-01,6:00:00,eq_2,chamber_1,w_6,p-type,5,1047.754819,72.688192,0.219864,4556.002443,403.046333,2.241902,0,none,2025-01-01 06:00:00
7,2025-01-01,7:00:00,eq_3,chamber_2,w_7,p-type,4,948.356539,36.511521,0.335200,3277.219938,231.376232,1.405614,0,none,2025-01-01 07:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,2025-02-11,9:00:00,eq_4,chamber_1,w_993,p-type,4,1021.380864,5.770236,0.723628,1779.361967,212.991414,0.412049,0,none,2025-02-11 09:00:00
994,2025-02-11,10:00:00,eq_5,chamber_2,w_994,p-type,5,921.932383,43.975700,0.988632,2965.321728,423.970025,1.594485,0,none,2025-02-11 10:00:00
995,2025-02-11,11:00:00,eq_1,chamber_3,w_995,n-type,4,1068.991935,52.783496,0.302645,4802.014246,464.065417,4.914362,0,none,2025-02-11 11:00:00
996,2025-02-11,12:00:00,eq_2,chamber_1,w_996,p-type,5,976.739157,55.965298,0.696086,2534.436161,261.114871,3.471068,0,none,2025-02-11 12:00:00
997,2025-02-11,13:00:00,eq_3,chamber_2,w_997,n-type,3,985.560235,45.612643,0.648714,2697.488104,310.582879,0.294383,0,none,2025-02-11 13:00:00

In [40]:
oxide_thickness = oxide_df['oxide_thickness']

target_thickness = oxide_thickness.median()
print(f"목표값: {target_thickness:.2f}")

std_thickness = oxide_thickness.std()
print(f"표준 편차: {std_thickness:.2f}")

# 허용 범위
lower_limit = target_thickness - 3 * std_thickness  # 하한 값 (목표 값 - 3σ)
upper_limit = target_thickness + 3 * std_thickness  # 상한 값 (목표 값 + 3σ)

print(f"허용 범위: {lower_limit:.2f} ~ {upper_limit:.2f}")

목표값: 310.52
표준 편차: 91.63
허용 범위: 35.61 ~ 585.42